name: Seva Auth
on:
  push:
    branches:
      - feat/*
jobs:
  tests:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-java@v1
      with:
        java-version: '12.x'
    - uses: subosito/flutter-action@v1
      with:
        flutter-version: '3.10.2'
        channel: 'stable'
    - name: Flutter Tests
      run: |
        flutter test